"use client";

import { useState } from "react";
import { AlertTriangle, ArrowRight, BarChart3, CalendarClock, Clock3, LogOut, RefreshCw, Sparkles, Target, TrendingDown, TrendingUp, UserCheck, UserMinus, Users, UsersRound } from "lucide-react";
import { weeklyPerformance, type AppScreen, type Crew, type LeaderUser, type Worker } from "@/data/agronexData";
import { DonutProgress, InfoStat, MetricCard, ProgressBar, ScreenHeading, SectionTitle, StatusBadge } from "./ui";
import { RegisterProgressForm, type ProgressSubmission } from "./register-form";

type LeaderProps = { leader: LeaderUser; crew: Crew; workers: Worker[] };

export function LeaderHome({ leader, crew, workers, onNavigate }: LeaderProps & { onNavigate: (screen: AppScreen) => void }) {
  const present = workers.filter((worker) => worker.attendance === "Presente").length;
  const absent = workers.length - present;
  const manHours = workers.reduce((sum, worker) => sum + worker.hoursWorked, 0);
  const average = present ? crew.progress / present : 0;
  return <div className="space-y-6"><ScreenHeading eyebrow="Mi jornada" title={`Buenos días, ${leader.name}`} description={`Tu labor asignada hoy: ${crew.labor}`} /><section className="rounded-3xl bg-[linear-gradient(135deg,#174d38,#267852)] p-5 text-white shadow-lg shadow-[#164a35]/15 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-widest text-white/55">Tarea asignada</p><h2 className="mt-2 text-xl font-extrabold">{crew.labor} · {crew.sector}</h2><p className="mt-1 text-sm text-white/65">{crew.crop} · {crew.name}</p></div><DonutProgress value={crew.percentage} size={96} /></div><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl bg-white/10 p-3"><HeroStat label="Meta del día" value={`${crew.goal} ${crew.unit}`} /><HeroStat label="Avance realizado" value={`${crew.progress} ${crew.unit}`} /><HeroStat label="Falta completar" value={`${crew.remaining} ${crew.unit}`} /></div></section><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><MetricCard label="Trabajadores asignados" value={String(workers.length)} icon={Users} /><MetricCard label="Trabajadores presentes" value={String(present)} icon={UserCheck} tone="green" /><MetricCard label="Ausentes" value={String(absent)} icon={UserMinus} tone="red" /><MetricCard label="Horas hombre" value={String(manHours)} icon={Clock3} tone="blue" /><MetricCard label="Rendimiento promedio" value={`${formatNumber(average)} ${crew.unit}/persona`} icon={TrendingUp} tone="gold" /><MetricCard label="Faltante" value={`${crew.remaining} ${crew.unit}`} icon={Target} tone="red" /></div><div className="grid gap-5 lg:grid-cols-2"><section className="ag-card p-5 sm:p-6"><SectionTitle title="Avance del día" /><div className="flex items-center justify-between text-sm"><span className="font-semibold text-[#60736a]">Meta vs. avance</span><strong>{crew.percentage}%</strong></div><div className="mt-3"><ProgressBar value={crew.percentage} /></div><div className="mt-5 grid grid-cols-3 gap-3"><InfoStat label="Meta" value={`${crew.goal} ${crew.unit}`} /><InfoStat label="Realizado" value={`${crew.progress} ${crew.unit}`} /><InfoStat label="Pendiente" value={`${crew.remaining} ${crew.unit}`} /></div><button onClick={() => onNavigate("registrar")} className="ag-primary mt-6 w-full">Registrar avance <ArrowRight size={17} /></button></section><section className="rounded-2xl border border-[#ead8af] bg-[#fff8e7] p-5 sm:p-6"><span className="grid size-10 place-items-center rounded-xl bg-white text-[#a66b00]"><Sparkles size={19} /></span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-[#9a6506]">Pendiente para mañana</p><p className="mt-2 text-sm font-semibold leading-6 text-[#5d5134]">Faltan {crew.remaining} {crew.unit}. Para mañana se sugiere completar la meta diaria y recuperar el pendiente.</p></section></div></div>;
}

export function LeaderRegister({ leader, crew, workers, onSave }: LeaderProps & { onSave: (submission: ProgressSubmission) => void }) {
  return <div><ScreenHeading eyebrow="Registro de campo" title="Guardar avance" description="Actualiza el total de la cuadrilla y el detalle por trabajador." /><RegisterProgressForm leader={leader} crew={crew} initialWorkers={workers} onSave={onSave} /></div>;
}

export function MyCrewScreen({ leader, crew, workers }: LeaderProps) {
  const present = workers.filter((worker) => worker.attendance === "Presente").length;
  const manHours = workers.reduce((sum, worker) => sum + worker.hoursWorked, 0);
  const average = present ? crew.progress / present : 0;
  return <div><ScreenHeading eyebrow="Equipo asignado" title="Mi cuadrilla" description="Asistencia y productividad de tu equipo durante la jornada." /><section className="ag-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-extrabold text-[#173c2d]">{crew.name}</h2><p className="mt-1 text-sm text-[#718078]">{leader.name} · {crew.labor} · {crew.sector}</p></div><StatusBadge status={crew.status} /></div><div className="my-5 grid grid-cols-2 gap-3 rounded-2xl bg-[#f6f8f6] p-4 sm:grid-cols-4"><InfoStat label="Trabajadores" value={String(workers.length)} /><InfoStat label="Presentes" value={String(present)} /><InfoStat label="Ausentes" value={String(workers.length - present)} /><InfoStat label="Horas hombre" value={String(manHours)} /><InfoStat label="Meta del día" value={`${crew.goal} ${crew.unit}`} /><InfoStat label="Avance" value={`${crew.progress} ${crew.unit}`} /><InfoStat label="Faltante" value={`${crew.remaining} ${crew.unit}`} /><InfoStat label="Promedio" value={`${formatNumber(average)} ${crew.unit}`} /></div><div className="flex justify-between text-xs font-semibold text-[#61736a]"><span>Cumplimiento</span><strong>{crew.percentage}%</strong></div><div className="mt-2"><ProgressBar value={crew.percentage} /></div></section><section className="mt-5"><SectionTitle title="Trabajadores de la cuadrilla" /><WorkerList workers={workers} crew={crew} /></section></div>;
}

export function MyWorkersScreen({ crew, workers }: { crew: Crew; workers: Worker[] }) {
  const [filter, setFilter] = useState("Todos");
  const average = workers.filter((item) => item.attendance === "Presente").reduce((sum, item) => sum + item.dailyOutput, 0) / Math.max(1, workers.filter((item) => item.attendance === "Presente").length);
  const visible = workers.filter((worker) => filter === "Todos" || (filter === "Presentes" && worker.attendance === "Presente") || (filter === "Ausentes" && worker.attendance === "Ausente") || (filter === "Alto rendimiento" && worker.dailyOutput > average * 1.05) || (filter === "Bajo rendimiento" && worker.attendance === "Presente" && worker.dailyOutput < average * .9));
  return <div><ScreenHeading eyebrow="Mi equipo" title="Mis trabajadores" description={`Solo trabajadores de ${crew.name}.`} /><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{["Todos", "Presentes", "Ausentes", "Alto rendimiento", "Bajo rendimiento"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`min-h-10 whitespace-nowrap rounded-full px-4 text-xs font-bold ${filter === item ? "bg-[#1a5b40] text-white" : "border border-[#dfe7e1] bg-white text-[#587066]"}`}>{item}</button>)}</div><WorkerList workers={visible} crew={crew} /></div>;
}

export function LeaderPerformance({ leader, crew, workers }: LeaderProps) {
  const weekly = weeklyPerformance.filter((item) => item.userId === leader.id);
  const present = workers.filter((worker) => worker.attendance === "Presente");
  const average = present.reduce((sum, worker) => sum + worker.dailyOutput, 0) / Math.max(1, present.length);
  const ranked = [...present].sort((a, b) => b.dailyOutput - a.dailyOutput);
  return <div><ScreenHeading eyebrow="Análisis personal" title="Rendimiento" description="Cumplimiento y productividad de tu cuadrilla." /><div className="grid gap-5 lg:grid-cols-2"><section className="ag-card p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-[#60736a]">Cumplimiento del día</p><p className="mt-2 text-3xl font-extrabold text-[#173c2d]">{crew.percentage}%</p></div><DonutProgress value={crew.percentage} size={112} /></div><div className="mt-5 grid grid-cols-3 gap-3"><InfoStat label="Meta" value={`${crew.goal} ${crew.unit}`} /><InfoStat label="Avance" value={`${crew.progress} ${crew.unit}`} /><InfoStat label="Promedio" value={`${formatNumber(average)} ${crew.unit}`} /></div></section><section className="ag-card p-5 sm:p-6"><SectionTitle title="Rendimiento semanal" /><div className="flex h-40 items-end gap-2 border-b border-[#e4ebe6] px-1">{weekly.map((item) => <div key={item.day} className="flex h-full flex-1 flex-col items-center justify-end"><span className="mb-1 text-[10px] font-bold text-[#60736a]">{item.percentage}%</span><div className="w-full rounded-t-lg bg-[#2b9868]" style={{ height: `${item.percentage}%` }} /><span className="mt-2 text-[10px] font-semibold text-[#718078]">{item.day}</span></div>)}</div></section><RankingCard title="Mejores trabajadores" icon={TrendingUp} workers={ranked.slice(0, 4)} crew={crew} /><RankingCard title="Trabajadores con bajo avance" icon={TrendingDown} workers={ranked.slice(-4).reverse()} crew={crew} /></div><section className="mt-5 rounded-2xl bg-[#173c2d] p-5 text-white"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-[#f2c76e]" size={20} /><p className="text-sm font-semibold leading-6">Revisar distribución de personal. La cuadrilla tiene {crew.totalWorkers} trabajadores asignados y {crew.presentWorkers} presentes. El avance está en {crew.percentage}%, por lo que mañana se sugiere recuperar {crew.remaining} {crew.unit} pendientes.</p></div></section></div>;
}

export function LeaderPending({ crew }: { crew: Crew }) {
  return <div><ScreenHeading eyebrow="Próxima jornada" title="Pendientes" description="Trabajo que requiere continuidad mañana." /><section className="ag-card p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#2d8a61]">{crew.sector}</p><h2 className="mt-2 text-lg font-extrabold text-[#173c2d]">{crew.labor}</h2><p className="mt-1 text-sm text-[#718078]">{crew.name}</p></div><StatusBadge status={crew.remaining === 0 ? "Terminado" : "Pendiente"} /></div><div className="my-5 grid grid-cols-3 gap-3 rounded-xl bg-[#f6f8f6] p-4"><InfoStat label="Meta" value={`${crew.goal} ${crew.unit}`} /><InfoStat label="Avance" value={`${crew.progress} ${crew.unit}`} /><InfoStat label="Pendiente" value={`${crew.remaining} ${crew.unit}`} /></div><ProgressBar value={crew.percentage} /></section><section className="mt-5 rounded-2xl border border-[#ead8af] bg-[#fff8e7] p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#9a6506]">Recomendación</p><p className="mt-2 text-sm font-semibold leading-6 text-[#5d5134]">{crew.remaining > 0 ? `Completar ${crew.remaining} ${crew.unit} pendientes antes de iniciar una nueva asignación.` : "La tarea quedó completada. Solicita la siguiente asignación al Supervisor general."}</p></section></div>;
}

export function LeaderMore({ onNavigate, onChangeUser, onExit }: { onNavigate: (screen: AppScreen) => void; onChangeUser: () => void; onExit: () => void }) {
  return <div><ScreenHeading eyebrow="Opciones" title="Más" description="Accesos de tu cuenta y jornada." /><div className="ag-card divide-y divide-[#edf1ee]">{[{ label: "Mis trabajadores", description: "Asistencia y rendimiento individual", icon: UsersRound, action: () => onNavigate("trabajadores") }, { label: "Pendientes", description: "Continuidad para la próxima jornada", icon: CalendarClock, action: () => onNavigate("pendientes") }, { label: "Cambiar usuario", description: "Seleccionar otro encargado", icon: RefreshCw, action: onChangeUser }, { label: "Salir", description: "Volver a la bienvenida", icon: LogOut, action: onExit }].map(({ label, description, icon: Icon, action }) => <button key={label} onClick={action} className="flex min-h-[72px] w-full items-center gap-4 px-5 text-left hover:bg-[#f7f9f7]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#edf5f0] text-[#247a56]"><Icon size={19} /></span><span className="flex-1"><strong className="block text-sm text-[#294a3b]">{label}</strong><span className="mt-1 block text-xs text-[#7b8981]">{description}</span></span><ArrowRight size={17} className="text-[#8d9992]" /></button>)}</div><p className="mt-8 text-center text-[10px] font-semibold tracking-[.14em] text-[#9aa69f]">by Zidnex Digital</p></div>;
}

function WorkerList({ workers, crew }: { workers: Worker[]; crew: Crew }) { const average = crew.presentWorkers ? crew.progress / crew.presentWorkers : 0; return <div className="grid gap-3 md:grid-cols-2">{workers.map((worker) => <article key={worker.id} className="ag-card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-sm font-extrabold text-[#294a3b]">{worker.name}</h3><p className="mt-1 text-xs text-[#7b8981]">{worker.hoursWorked} horas trabajadas</p></div><StatusBadge status={worker.attendance} /></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-[#f7f9f7] p-3"><InfoStat label="Avance" value={`${worker.dailyOutput} ${worker.unit}`} /><InfoStat label="Rendimiento" value={worker.attendance === "Ausente" ? "Sin registro" : worker.dailyOutput >= average ? "Alto" : "En seguimiento"} /></div><p className="mt-3 text-xs leading-5 text-[#6c7d74]">{worker.observation}</p></article>)}</div>; }
function RankingCard({ title, icon: Icon, workers, crew }: { title: string; icon: typeof BarChart3; workers: Worker[]; crew: Crew }) { return <section className="ag-card p-5 sm:p-6"><div className="mb-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#e9f6ef] text-[#18794e]"><Icon size={18} /></span><h2 className="font-bold text-[#173c2d]">{title}</h2></div><div className="space-y-3">{workers.map((worker, index) => <div key={worker.id} className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-full bg-[#eff4f0] text-xs font-bold text-[#597067]">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-semibold text-[#355447]">{worker.name}</span><strong className="text-xs text-[#173c2d]">{worker.dailyOutput} {crew.unit}</strong></div>)}</div></section>; }
function HeroStat({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-wide text-white/50">{label}</p><p className="mt-1 truncate text-xs font-extrabold text-white">{value}</p></div>; }
function formatNumber(value: number) { return Number(value.toFixed(2)).toString(); }

