"use client";

import { useState } from "react";
import { BarChart3, CalendarClock, Check, ChevronRight, CircleAlert, ClipboardCheck, Lightbulb, Map, MoreHorizontal, Plus, Sparkles, Sprout, Target, TrendingUp, Users } from "lucide-react";
import { catalog, crewAssignments, laborProgress, metrics, pending, planningSuggestions, sectorOperations, type CrewAssignment, type OperationRecord } from "@/data/agronexData";
import { DonutProgress, MetricCard, ProgressBar, SectionTitle } from "./ui";
import { RegisterProgressForm } from "./register-form";

export function Dashboard({ navigate }: { navigate: (screen: "pendientes" | "sectores") => void }) {
  return <div className="space-y-6">
    <section><p className="text-sm font-medium text-[#708077]">Resumen operativo</p><div className="mt-1 flex items-end justify-between gap-3"><div><h1 className="ag-page-title">Buenos días, Carlos</h1><p className="mt-1 text-sm text-[#718078]">Operación consolidada de la jornada</p></div><span className="hidden rounded-full bg-[#e9f6ef] px-3 py-1.5 text-xs font-bold text-[#18794e] sm:block">Jornada activa</span></div></section>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="Cuadrillas activas" value={String(metrics.activeCrews)} icon={Users} /><MetricCard label="Sectores trabajados" value={String(metrics.workedSectors)} icon={Map} tone="blue" /><MetricCard label="Avance general" value={`${metrics.overallProgress}%`} icon={TrendingUp} tone="gold" /><MetricCard label="Pendientes" value={String(metrics.pendingCount)} icon={CircleAlert} tone="red" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <section className="ag-card p-5 sm:p-6"><SectionTitle title="Avance por labor" action={<button onClick={() => navigate("sectores")} className="ag-text-button">Ver sectores <ChevronRight size={15} /></button>} /><div className="grid gap-5 sm:grid-cols-2">{laborProgress.map((item) => <ProgressRow key={item.name} label={item.name} value={item.value} color={item.color} />)}</div></section>
      <section className="ag-card flex items-center justify-between gap-5 p-5 sm:p-6 xl:flex-col xl:text-center"><div><p className="text-sm font-semibold text-[#718078]">Cumplimiento del día</p><p className="mt-2 text-xs leading-5 text-[#8b978f]">Avance consolidado de todas las labores</p></div><DonutProgress value={metrics.overallProgress} size={122} /></section>
    </div>
    <section className="ag-card p-5 sm:p-6"><SectionTitle title="Avance por cuadrilla" /><div className="grid gap-3 md:grid-cols-2">{crewAssignments.map((crew) => <article key={crew.id} className="rounded-2xl bg-[#f6f8f6] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-extrabold text-[#294a3b]">{crew.crew}</h3><p className="mt-1 text-xs text-[#718078]">{crew.labor} · {crew.sector}</p></div><strong className="text-sm text-[#173c2d]">{crew.percent}%</strong></div><div className="mt-3"><ProgressBar value={crew.percent} color={crew.status === "Prioridad" ? "#d28a1b" : "#1f9d67"} /></div></article>)}</div></section>
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <section className="ag-card p-5 sm:p-6"><SectionTitle title="Pendientes para mañana" action={<button onClick={() => navigate("pendientes")} className="ag-text-button">Planificar <ChevronRight size={15} /></button>} /><div className="divide-y divide-[#edf1ee]">{pending.map((item) => <div key={item.sector} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#fff0ed] text-[#bd513c]"><CircleAlert size={17} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[#294a3b]">{item.sector} · {item.labor}</p><p className="mt-0.5 text-xs text-[#7c8b83]">Faltan {item.remaining}</p></div></div>)}</div></section>
      <section className="rounded-2xl bg-[linear-gradient(135deg,#1a5b40,#267852)] p-5 text-white shadow-lg shadow-[#164a35]/15"><span className="grid size-10 place-items-center rounded-xl bg-white/15"><Sparkles size={20} /></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-white/60">Sugerencia de planificación</p><p className="mt-2 font-semibold leading-7">Priorizar Lote 04 por menor cumplimiento y reforzar Bloque B3 por producción pendiente.</p></section>
    </div>
  </div>;
}

export function RegisterScreen({ crew, percent, onProgressUpdate, onChangeCrew }: { crew: CrewAssignment | null; percent: number; onProgressUpdate: (percent: number) => void; onChangeCrew: () => void }) {
  return <div><ScreenHeading eyebrow="Registro diario" title="Nuevo avance" description="Actualiza el trabajo realizado durante la jornada." />{crew && <section className="ag-card mb-5 overflow-hidden"><div className="border-l-4 border-[#24905f] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#2d8a61]">Reportando como</p><h2 className="mt-1 text-lg font-extrabold text-[#173c2d]">{crew.crew}</h2></div><button onClick={onChangeCrew} className="ag-text-button">Cambiar cuadrilla</button></div><div className="mt-4 grid grid-cols-3 gap-2"><SmallStat label="Labor" value={crew.labor} /><SmallStat label="Sector" value={crew.sector} /><SmallStat label="Avance actual" value={`${percent}%`} /></div><div className="mt-4"><ProgressBar value={percent} /></div></div></section>}<RegisterProgressForm crew={crew} onProgressUpdate={onProgressUpdate} /></div>;
}

export function SectorsScreen({ crew, sessionPercent }: { crew: CrewAssignment | null; sessionPercent: number }) {
  const [filter, setFilter] = useState("Todos");
  const assignedRecord: OperationRecord | null = crew ? { ...crew, percent: sessionPercent, progress: Math.round((crew.goal * sessionPercent / 100) * 100) / 100, remaining: Math.max(0, Math.round((crew.goal * (100 - sessionPercent) / 100) * 100) / 100) } : null;
  const visibleSectors = assignedRecord ? [assignedRecord] : sectorOperations;
  return <div><ScreenHeading eyebrow={crew ? "Asignación de cuadrilla" : "Supervisión de campo"} title={crew ? "Mis sectores" : "Sectores"} description={crew ? `Información operativa de ${crew.crew}.` : "Estado operativo por sector y labor."} />{!crew && <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{["Todos", "En proceso", "Prioridad", "Terminado"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold transition ${filter === item ? "bg-[#1a5b40] text-white" : "border border-[#dfe7e1] bg-white text-[#587066]"}`}>{item}</button>)}</div>}<div className="grid gap-4 lg:grid-cols-2">{visibleSectors.filter((item) => filter === "Todos" || item.status === filter).map((item) => <SectorCard key={item.id} item={item} />)}</div>{crew && <section className="mt-5 rounded-2xl border border-[#ead8af] bg-[#fff8e7] p-5"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-[#a66b00]"><ClipboardCheck size={19} /></span><div><p className="text-xs font-bold uppercase tracking-wider text-[#9a6506]">Pendiente para mañana</p><p className="mt-2 text-sm font-semibold leading-6 text-[#5d5134]">{crew.tomorrow}</p></div></div></section>}</div>;
}

export function PendingScreen() {
  return <div><ScreenHeading eyebrow="Próxima jornada" title="Pendientes para mañana" description="Labores que necesitan continuidad o refuerzo." /><div className="grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="space-y-3">{pending.map((item, index) => <article key={item.sector} className="ag-card flex items-center gap-4 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#f0f5f1] font-extrabold text-[#1f6c4b]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-[#244637]">{item.sector}</h3><Status status={item.priority === "Alta" ? "Prioridad" : "Pendiente"} /></div><p className="mt-1 text-sm text-[#718078]">{item.labor} · faltan <strong className="text-[#4a6257]">{item.remaining}</strong></p></div></article>)}</div><section><SectionTitle title="Sugerencia de planificación" /><div className="space-y-3">{planningSuggestions.map((suggestion, index) => <article key={suggestion} className={`rounded-2xl p-4 ${index === 0 ? "bg-[#1a5b40] text-white" : "ag-card text-[#355447]"}`}><div className="flex gap-3"><Lightbulb size={18} className={index === 0 ? "text-[#bce8cb]" : "text-[#2d8a61]"} /><p className="text-sm font-semibold leading-6">{suggestion}</p></div></article>)}</div></section></div></div>;
}

export function ReportsScreen() {
  return <div><ScreenHeading eyebrow="Análisis operativo" title="Reportes" description="Indicadores para tomar decisiones de campo." /><div className="grid gap-5 lg:grid-cols-2"><ReportBars title="Avance por labor" icon={BarChart3} data={laborProgress.map((item) => ({ label: item.name, value: item.value }))} /><ReportBars title="Cumplimiento por cuadrilla" icon={Users} data={crewAssignments.map((item) => ({ label: item.crew, value: item.percent }))} /><ReportBars title="Avance por sector" icon={Map} data={sectorOperations.map((item) => ({ label: item.sector, value: item.percent }))} /><section className="ag-card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#edf5fc] text-[#3271a8]"><CalendarClock size={18} /></span><h2 className="font-bold text-[#173c2d]">Comparativo operativo del día</h2></div><div className="mt-7 flex h-44 items-end justify-around gap-5 border-b border-[#e4ebe6] px-3"><DayBar label="Ayer" value={68} /><DayBar label="Hoy" value={76} active /><DayBar label="Meta" value={90} /></div><div className="mt-8 flex items-center gap-2 rounded-xl bg-[#e9f6ef] p-3 text-xs font-semibold text-[#18794e]"><TrendingUp size={16} />8% más avance respecto a la jornada anterior</div></section></div></div>;
}

export function AdminConfigPanel() {
  const initial = { cultivos: catalog.cultivos, sectores: catalog.sectores, labores: catalog.labores, cuadrillas: catalog.cuadrillas, unidades: catalog.unidades };
  const [data, setData] = useState(initial); const [active, setActive] = useState<keyof typeof initial>("cultivos"); const [input, setInput] = useState("");
  const add = () => { const clean = input.trim(); if (!clean) return; const next = { ...data, [active]: [...data[active], clean] }; setData(next); localStorage.setItem("agronex-catalog", JSON.stringify(next)); setInput(""); };
  return <div><ScreenHeading eyebrow="Administración" title="Configuración" description="Gestiona los catálogos utilizados en campo." /><div className="grid gap-5 lg:grid-cols-[240px_1fr]"><nav className="ag-card flex gap-2 overflow-x-auto p-2 lg:block lg:space-y-1">{(Object.keys(data) as (keyof typeof data)[]).map((key) => <button key={key} onClick={() => setActive(key)} className={`flex w-full min-w-max items-center justify-between rounded-xl px-4 py-3 text-left text-sm font-bold capitalize transition ${active === key ? "bg-[#e9f6ef] text-[#18794e]" : "text-[#61736a] hover:bg-[#f5f7f5]"}`}><span>{key}</span><span className="ml-4 text-xs opacity-60">{data[key].length}</span></button>)}</nav><section className="ag-card p-5 sm:p-6"><SectionTitle title={active.charAt(0).toUpperCase() + active.slice(1)} /><div className="mb-5 flex gap-2"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === "Enter" && add()} className="h-11 flex-1 rounded-xl border border-[#dbe5de] px-3.5 text-sm outline-none focus:border-[#238358]" placeholder={`Nuevo registro en ${active}`} /><button onClick={add} className="ag-primary h-11 px-4"><Plus size={18} /><span className="hidden sm:inline">Agregar</span></button></div><div className="divide-y divide-[#edf1ee]">{data[active].map((item) => <div key={item} className="flex items-center justify-between py-3"><div className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-full bg-[#eff4f0] text-[#4c6b5d]"><Check size={14} /></span><span className="text-sm font-semibold text-[#355447]">{item}</span></div><button aria-label={`Opciones de ${item}`}><MoreHorizontal size={18} className="text-[#8c9991]" /></button></div>)}</div></section></div></div>;
}

function SectorCard({ item }: { item: OperationRecord }) { return <article className="ag-card overflow-hidden p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#e9f6ef] text-[#18794e]"><Sprout size={19} /></span><div><h3 className="font-bold text-[#173c2d]">{item.sector}</h3><p className="mt-0.5 text-xs text-[#74837b]">{item.crop} · {item.labor}</p></div></div><Status status={item.status} /></div><div className="my-5 grid grid-cols-3 gap-2 rounded-xl bg-[#f6f8f6] p-3 text-center"><SmallStat label="Meta" value={`${item.goal} ${item.unit}`} /><SmallStat label="Avance" value={`${item.progress} ${item.unit}`} /><SmallStat label="Faltante" value={`${item.remaining} ${item.unit}`} /></div><div className="mb-2 flex justify-between text-xs font-semibold text-[#61736a]"><span>Cumplimiento</span><strong className="text-[#173c2d]">{item.percent}%</strong></div><ProgressBar value={item.percent} color={item.status === "Prioridad" ? "#d28a1b" : "#1f9d67"} />{item.observation && <p className="mt-4 rounded-xl bg-[#f7f9f7] px-3 py-2 text-xs leading-5 text-[#6b7c73]"><strong>Observación:</strong> {item.observation}</p>}</article>; }
function ScreenHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#2d8a61]">{eyebrow}</p><h1 className="ag-page-title mt-2">{title}</h1><p className="mt-2 text-sm text-[#718078]">{description}</p></header>; }
function SmallStat({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#8a978f]">{label}</p><p className="mt-1 truncate text-xs font-bold text-[#355447]">{value}</p></div>; }
function Status({ status }: { status: string }) { const style = status === "Terminado" ? "bg-[#e8f6ee] text-[#18794e]" : status === "Prioridad" ? "bg-[#fff0ed] text-[#bd513c]" : status === "En proceso" ? "bg-[#fff5dd] text-[#9a6506]" : "bg-[#edf2f8] text-[#50708f]"; return <span className={`whitespace-nowrap rounded-full px-2.5 py-1 text-[10px] font-bold ${style}`}>{status}</span>; }
function ProgressRow({ label, value, color = "#1f9d67" }: { label: string; value: number; color?: string }) { return <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-[#355447]">{label}</span><strong className="text-[#173c2d]">{value}%</strong></div><ProgressBar value={value} color={color} /></div>; }
function ReportBars({ title, icon: Icon, data }: { title: string; icon: typeof Target; data: { label: string; value: number }[] }) { return <section className="ag-card p-5 sm:p-6"><div className="mb-6 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#e9f6ef] text-[#18794e]"><Icon size={18} /></span><h2 className="font-bold text-[#173c2d]">{title}</h2></div><div className="space-y-5">{data.map((item) => <ProgressRow key={item.label} label={item.label} value={item.value} />)}</div></section>; }
function DayBar({ label, value, active }: { label: string; value: number; active?: boolean }) { return <div className="flex h-full w-20 flex-col items-center justify-end"><strong className="mb-2 text-sm text-[#355447]">{value}%</strong><div className={`w-full rounded-t-xl ${active ? "bg-[#1f9d67]" : "bg-[#cddbd2]"}`} style={{ height: `${value}%` }} /><span className="absolute mt-6 translate-y-7 text-xs font-semibold text-[#718078]">{label}</span></div>; }
