"use client";

import { ArrowLeft, ChevronRight, MapPin, UserRound } from "lucide-react";
import { getCrewForLeader, leaders, type LeaderUser } from "@/data/agronexData";
import { AgroLogo } from "./brand";
import { ProgressBar, StatusBadge } from "./ui";

export function UserSelector({ onBack, onSelect }: { onBack: () => void; onSelect: (leader: LeaderUser) => void }) {
  return <main className="min-h-dvh bg-[#f3f6f3] px-5 pb-[max(2rem,env(safe-area-inset-bottom))] pt-[max(1.75rem,env(safe-area-inset-top))]"><div className="mx-auto w-full max-w-4xl"><div className="flex items-center justify-between"><AgroLogo /><button onClick={onBack} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-xs font-bold text-[#587066] hover:bg-white"><ArrowLeft size={16} />Volver</button></div><header className="mb-7 mt-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#2d8a61]">Acceso de campo</p><h1 className="ag-page-title mt-2">Selecciona tu usuario</h1><p className="mt-2 text-sm text-[#718078]">Ingresa al panel de tu labor asignada.</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{leaders.map((leader) => { const crew = getCrewForLeader(leader.id); return <button key={leader.id} onClick={() => onSelect(leader)} className="ag-card group p-5 text-left transition hover:-translate-y-0.5 hover:border-[#bcd3c4] hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#e9f6ef] text-[#18794e]"><UserRound size={20} /></span><StatusBadge status={crew.status} /></div><h2 className="mt-4 text-lg font-extrabold text-[#244637]">{leader.name}</h2><p className="mt-1 text-sm font-semibold text-[#567064]">Encargado de {leader.labor.toLowerCase()}</p><p className="mt-2 flex items-center gap-1.5 text-xs text-[#7a8981]"><MapPin size={14} />{leader.crop} · {leader.sector}</p><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-[#f6f8f6] p-3 text-xs"><div><span className="text-[#819087]">Cuadrilla</span><strong className="mt-1 block truncate text-[#355447]">{leader.crewName}</strong></div><div><span className="text-[#819087]">Meta del día</span><strong className="mt-1 block text-[#355447]">{crew.goal} {crew.unit}</strong></div></div><div className="mt-4 flex justify-between text-xs font-semibold text-[#61736a]"><span>Avance actual</span><strong className="text-[#173c2d]">{crew.percentage}%</strong></div><div className="mt-2"><ProgressBar value={crew.percentage} color={crew.status === "Prioridad" ? "#d28a1b" : "#1f9d67"} /></div><span className="mt-5 flex items-center justify-end gap-1 text-xs font-bold text-[#25805a]">Ingresar <ChevronRight size={15} className="transition group-hover:translate-x-0.5" /></span></button>; })}</div><p className="mt-8 text-center text-[10px] font-semibold tracking-[.14em] text-[#9aa69f]">by Zidnex Digital</p></div></main>;
}
